# Paths used
images_path: data/temp/windowed_ti/
checkpoint: .checkpoints/wgan_gp
sample_images: sample_images/wgan_gp
training_image: data/TI/strebelle.png
output_dir: data/temp/windowed_ti/real/

# Training parameters
n_epochs: 20
cuda: False
batch_size: 128
num_workers: 4
n_critic: 5
num_channels: 1
learning_rate: 0.0002
latent_dim: 100
img_size: (64, 64)
